---
- name: ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ base_dir }}/sonar/data"
  - "{{ base_dir }}/sonar/conf"
- name: create sonar database container
  docker:
    name: sonar-mysql
    hostname: sonar-mysql
    image: docker-registry:5000/library/mysql:5.6.22
    state: running
    env:
      MYSQL_ROOT_PASSWORD: salam
      MYSQL_DATABASE: sonar
    volumes:
    - "{{ base_dir }}/sonar/db/:/var/lib/mysql"
- name: fetch sonar archive
  get_url:
    url: "http://samat-server.devsamat.ir/repo/sonarqube-5.1.1.zip"
    sha256sum: "8626ff7b4eaf8aba92856b27ed0cdcea432d5596bd1ac167ec27cce70ad0557f"
    dest: "{{ base_dir }}/sonar/"
- name: unzip sonar archive
  unarchive:
    copy: no
    src: "{{ base_dir }}/sonar/sonarqube-5.1.1.zip"
    dest: "{{ base_dir }}/sonar/data/"
    creates: "{{ base_dir }}/sonar/data/sonarqube-5.1.1"
- name: Sync sonar conf
  copy:
    src: conf/
    dest: "{{base_dir}}/sonar/conf/"
- name: create sonar container
  docker:
    name: sonar
    hostname: sonar
    docker_api_version: "{{docker_api_version}}"
    dns:
    - "{{dns_addr}}"
    dns_search:
    - "{{dns_search}}"image: docker-registry:5000/library/java7-oracle:1.3
    volumes:
    - "{{ base_dir }}/sonar/data/sonarqube-5.1.1/:/opt/sonar"
    - "{{ base_dir }}/sonar/conf/:/opt/sonar/conf"
    links:
    - "sonar-mysql"
    command: "/opt/sonar/bin/linux-x86-64/sonar.sh console"
