---
- name: Sync nginx conf
  copy:
    src: conf/
    dest: "{{base_dir}}/nginx-phantom/conf/"
  register: sync_conf
- name: run nginx-phantom.mehriz-server container
  docker:
    image: docker-registry:5000/library/nginx:1.7.10
    name: nginx-phantom.mehriz-server
    hostname: nginx-phantom.mehriz-server
    docker_api_version: "{{docker_api_version}}"
    dns:
    - "{{dns_addr}}"
    dns_search:
    - "{{dns_search}}"
    state: "{{ 'restarted' if sync_conf.changed else 'running' }}"
    env:
      ARTIFACT_ID: "{{artifact_id}}"
    volumes:
    - "{{base_dir}}/nginx-phantom/conf:/etc/nginx/conf.d"
