---
- name: ensure directory exists
  file:
    path: "{{ base_dir }}/gogs/{{ item }}"
    state: directory
  with_items:
  - data
  - db
- name: create gogs mysql container
  docker:
    name: gogs-mysql
    docker_api_version: "{{docker_api_version}}"
    hostname: gogs-mysql
    image: docker-registry:5000/library/mysql:5.6.22
    state: running
    env:
      MYSQL_ROOT_PASSWORD: salam
      MYSQL_DATABASE: gogs
    volumes:
    - "{{ base_dir }}/gogs/db:/var/lib/mysql"
- name: create gogs container
  docker:
    image: docker-registry:5000/official/codeskyblue-docker-gogs:latest
    name: gogs
    docker_api_version: "{{docker_api_version}}"
    dns:
    - "{{dns_addr}}"
    dns_search:
    - "{{dns_search}}"
    hostname: gogs
    ports:
    - "10022:22"
    - "10080:3000"
    volumes:
    - "{{ base_dir }}/gogs/data:/data"
