---
- name: ensure directory exists
  file:
    path: "{{ base_dir }}/squid/store"
    state: directory
- name: create squid container
  docker:
    image: docker-registry:5000/official/sameersbn-squid:latest
    name: squid
    hostname: squid
    docker_api_version: "{{docker_api_version}}"
    dns:
    - "{{dns_addr}}"
    dns_search:
    - "{{dns_search}}"env:
      CACHE_MAX_SIZE: 1000
    ports:
    - "3128:3128"
    volumes:
    - "{{ base_dir }}/squid/store:/var/spool/squid3"